services:
  auth-db:
    container_name: auth-db
    image: postgres:16
    restart: always
    env_file: .env
    networks:
      - my_net
    expose:
      - "$POSTGRES_PORT"
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    volumes:
      - ./data:/var/lib/postgresql/data

  auth-web:
    container_name: auth-app
    depends_on:
      - auth-db
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "$APP_PORT:$APP_PORT"
    networks:
      - my_net
    restart: unless-stopped
    volumes:
      - .:/app

networks:
  my_net:

volumes:
  postgres_data:
