services:
  auth-db:
    container_name: auth-db
    image: postgres:14
    restart: always
    env_file: .env
    networks:
      - my_net
    expose:
      - "$POSTGRES_PORT"
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-app:
    container_name: auth-app
    image: auth-app:latest
    depends_on:
      - auth-db
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "$APP_PORT:$APP_PORT"
    networks:
      - my_net
    restart: unless-stopped
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  auth-nginx:
    container_name: auth-nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "8080:80"
    depends_on:
      - auth-app
    networks:
      - my_net

networks:
  my_net:

volumes:
  postgres_data:
